// Single source of truth for countries: canonical name, flag, and international
// dialing code. The document Country dropdown (COUNTRIES) and the name→phone-code
// lookup (countryNameToCC) are both DERIVED from this list, so they can never
// drift out of sync — picking any country in the dropdown always yields a
// sensible default code on the Phone screen.
//
// Names for the countries the OCR parser can emit (see ISO3_TO_NAME in
// ocrParse.ts) are kept identical here so an OCR-detected country pre-selects in
// the dropdown: "United States", "United Kingdom", "South Korea", "UAE",
// "Czech Republic", "Slovakia", etc.

export interface Country {
  name: string;
  flag: string;
}

interface CountryData extends Country {
  cc: string; // international dialing code, e.g. "+1"
}

// Complete ISO 3166 list (UN members + commonly-travelled territories),
// alphabetical by display name.
const ALL: CountryData[] = [
  { name: "Afghanistan", flag: "🇦🇫", cc: "+93" },
  { name: "Albania", flag: "🇦🇱", cc: "+355" },
  { name: "Algeria", flag: "🇩🇿", cc: "+213" },
  { name: "Andorra", flag: "🇦🇩", cc: "+376" },
  { name: "Angola", flag: "🇦🇴", cc: "+244" },
  { name: "Antigua and Barbuda", flag: "🇦🇬", cc: "+1" },
  { name: "Argentina", flag: "🇦🇷", cc: "+54" },
  { name: "Armenia", flag: "🇦🇲", cc: "+374" },
  { name: "Australia", flag: "🇦🇺", cc: "+61" },
  { name: "Austria", flag: "🇦🇹", cc: "+43" },
  { name: "Azerbaijan", flag: "🇦🇿", cc: "+994" },
  { name: "Bahamas", flag: "🇧🇸", cc: "+1" },
  { name: "Bahrain", flag: "🇧🇭", cc: "+973" },
  { name: "Bangladesh", flag: "🇧🇩", cc: "+880" },
  { name: "Barbados", flag: "🇧🇧", cc: "+1" },
  { name: "Belarus", flag: "🇧🇾", cc: "+375" },
  { name: "Belgium", flag: "🇧🇪", cc: "+32" },
  { name: "Belize", flag: "🇧🇿", cc: "+501" },
  { name: "Benin", flag: "🇧🇯", cc: "+229" },
  { name: "Bhutan", flag: "🇧🇹", cc: "+975" },
  { name: "Bolivia", flag: "🇧🇴", cc: "+591" },
  { name: "Bosnia and Herzegovina", flag: "🇧🇦", cc: "+387" },
  { name: "Botswana", flag: "🇧🇼", cc: "+267" },
  { name: "Brazil", flag: "🇧🇷", cc: "+55" },
  { name: "Brunei", flag: "🇧🇳", cc: "+673" },
  { name: "Bulgaria", flag: "🇧🇬", cc: "+359" },
  { name: "Burkina Faso", flag: "🇧🇫", cc: "+226" },
  { name: "Burundi", flag: "🇧🇮", cc: "+257" },
  { name: "Cambodia", flag: "🇰🇭", cc: "+855" },
  { name: "Cameroon", flag: "🇨🇲", cc: "+237" },
  { name: "Canada", flag: "🇨🇦", cc: "+1" },
  { name: "Cape Verde", flag: "🇨🇻", cc: "+238" },
  { name: "Central African Republic", flag: "🇨🇫", cc: "+236" },
  { name: "Chad", flag: "🇹🇩", cc: "+235" },
  { name: "Chile", flag: "🇨🇱", cc: "+56" },
  { name: "China", flag: "🇨🇳", cc: "+86" },
  { name: "Colombia", flag: "🇨🇴", cc: "+57" },
  { name: "Comoros", flag: "🇰🇲", cc: "+269" },
  { name: "Congo (Brazzaville)", flag: "🇨🇬", cc: "+242" },
  { name: "Congo (Kinshasa)", flag: "🇨🇩", cc: "+243" },
  { name: "Costa Rica", flag: "🇨🇷", cc: "+506" },
  { name: "Croatia", flag: "🇭🇷", cc: "+385" },
  { name: "Cuba", flag: "🇨🇺", cc: "+53" },
  { name: "Cyprus", flag: "🇨🇾", cc: "+357" },
  { name: "Czech Republic", flag: "🇨🇿", cc: "+420" },
  { name: "Denmark", flag: "🇩🇰", cc: "+45" },
  { name: "Djibouti", flag: "🇩🇯", cc: "+253" },
  { name: "Dominica", flag: "🇩🇲", cc: "+1" },
  { name: "Dominican Republic", flag: "🇩🇴", cc: "+1" },
  { name: "Ecuador", flag: "🇪🇨", cc: "+593" },
  { name: "Egypt", flag: "🇪🇬", cc: "+20" },
  { name: "El Salvador", flag: "🇸🇻", cc: "+503" },
  { name: "Equatorial Guinea", flag: "🇬🇶", cc: "+240" },
  { name: "Eritrea", flag: "🇪🇷", cc: "+291" },
  { name: "Estonia", flag: "🇪🇪", cc: "+372" },
  { name: "Eswatini", flag: "🇸🇿", cc: "+268" },
  { name: "Ethiopia", flag: "🇪🇹", cc: "+251" },
  { name: "Fiji", flag: "🇫🇯", cc: "+679" },
  { name: "Finland", flag: "🇫🇮", cc: "+358" },
  { name: "France", flag: "🇫🇷", cc: "+33" },
  { name: "Gabon", flag: "🇬🇦", cc: "+241" },
  { name: "Gambia", flag: "🇬🇲", cc: "+220" },
  { name: "Georgia", flag: "🇬🇪", cc: "+995" },
  { name: "Germany", flag: "🇩🇪", cc: "+49" },
  { name: "Ghana", flag: "🇬🇭", cc: "+233" },
  { name: "Greece", flag: "🇬🇷", cc: "+30" },
  { name: "Grenada", flag: "🇬🇩", cc: "+1" },
  { name: "Guatemala", flag: "🇬🇹", cc: "+502" },
  { name: "Guinea", flag: "🇬🇳", cc: "+224" },
  { name: "Guinea-Bissau", flag: "🇬🇼", cc: "+245" },
  { name: "Guyana", flag: "🇬🇾", cc: "+592" },
  { name: "Haiti", flag: "🇭🇹", cc: "+509" },
  { name: "Honduras", flag: "🇭🇳", cc: "+504" },
  { name: "Hong Kong", flag: "🇭🇰", cc: "+852" },
  { name: "Hungary", flag: "🇭🇺", cc: "+36" },
  { name: "Iceland", flag: "🇮🇸", cc: "+354" },
  { name: "India", flag: "🇮🇳", cc: "+91" },
  { name: "Indonesia", flag: "🇮🇩", cc: "+62" },
  { name: "Iran", flag: "🇮🇷", cc: "+98" },
  { name: "Iraq", flag: "🇮🇶", cc: "+964" },
  { name: "Ireland", flag: "🇮🇪", cc: "+353" },
  { name: "Israel", flag: "🇮🇱", cc: "+972" },
  { name: "Italy", flag: "🇮🇹", cc: "+39" },
  { name: "Ivory Coast", flag: "🇨🇮", cc: "+225" },
  { name: "Jamaica", flag: "🇯🇲", cc: "+1" },
  { name: "Japan", flag: "🇯🇵", cc: "+81" },
  { name: "Jordan", flag: "🇯🇴", cc: "+962" },
  { name: "Kazakhstan", flag: "🇰🇿", cc: "+7" },
  { name: "Kenya", flag: "🇰🇪", cc: "+254" },
  { name: "Kiribati", flag: "🇰🇮", cc: "+686" },
  { name: "Kosovo", flag: "🇽🇰", cc: "+383" },
  { name: "Kuwait", flag: "🇰🇼", cc: "+965" },
  { name: "Kyrgyzstan", flag: "🇰🇬", cc: "+996" },
  { name: "Laos", flag: "🇱🇦", cc: "+856" },
  { name: "Latvia", flag: "🇱🇻", cc: "+371" },
  { name: "Lebanon", flag: "🇱🇧", cc: "+961" },
  { name: "Lesotho", flag: "🇱🇸", cc: "+266" },
  { name: "Liberia", flag: "🇱🇷", cc: "+231" },
  { name: "Libya", flag: "🇱🇾", cc: "+218" },
  { name: "Liechtenstein", flag: "🇱🇮", cc: "+423" },
  { name: "Lithuania", flag: "🇱🇹", cc: "+370" },
  { name: "Luxembourg", flag: "🇱🇺", cc: "+352" },
  { name: "Macau", flag: "🇲🇴", cc: "+853" },
  { name: "Madagascar", flag: "🇲🇬", cc: "+261" },
  { name: "Malawi", flag: "🇲🇼", cc: "+265" },
  { name: "Malaysia", flag: "🇲🇾", cc: "+60" },
  { name: "Maldives", flag: "🇲🇻", cc: "+960" },
  { name: "Mali", flag: "🇲🇱", cc: "+223" },
  { name: "Malta", flag: "🇲🇹", cc: "+356" },
  { name: "Marshall Islands", flag: "🇲🇭", cc: "+692" },
  { name: "Mauritania", flag: "🇲🇷", cc: "+222" },
  { name: "Mauritius", flag: "🇲🇺", cc: "+230" },
  { name: "Mexico", flag: "🇲🇽", cc: "+52" },
  { name: "Micronesia", flag: "🇫🇲", cc: "+691" },
  { name: "Moldova", flag: "🇲🇩", cc: "+373" },
  { name: "Monaco", flag: "🇲🇨", cc: "+377" },
  { name: "Mongolia", flag: "🇲🇳", cc: "+976" },
  { name: "Montenegro", flag: "🇲🇪", cc: "+382" },
  { name: "Morocco", flag: "🇲🇦", cc: "+212" },
  { name: "Mozambique", flag: "🇲🇿", cc: "+258" },
  { name: "Myanmar", flag: "🇲🇲", cc: "+95" },
  { name: "Namibia", flag: "🇳🇦", cc: "+264" },
  { name: "Nauru", flag: "🇳🇷", cc: "+674" },
  { name: "Nepal", flag: "🇳🇵", cc: "+977" },
  { name: "Netherlands", flag: "🇳🇱", cc: "+31" },
  { name: "New Zealand", flag: "🇳🇿", cc: "+64" },
  { name: "Nicaragua", flag: "🇳🇮", cc: "+505" },
  { name: "Niger", flag: "🇳🇪", cc: "+227" },
  { name: "Nigeria", flag: "🇳🇬", cc: "+234" },
  { name: "North Korea", flag: "🇰🇵", cc: "+850" },
  { name: "North Macedonia", flag: "🇲🇰", cc: "+389" },
  { name: "Norway", flag: "🇳🇴", cc: "+47" },
  { name: "Oman", flag: "🇴🇲", cc: "+968" },
  { name: "Pakistan", flag: "🇵🇰", cc: "+92" },
  { name: "Palau", flag: "🇵🇼", cc: "+680" },
  { name: "Palestine", flag: "🇵🇸", cc: "+970" },
  { name: "Panama", flag: "🇵🇦", cc: "+507" },
  { name: "Papua New Guinea", flag: "🇵🇬", cc: "+675" },
  { name: "Paraguay", flag: "🇵🇾", cc: "+595" },
  { name: "Peru", flag: "🇵🇪", cc: "+51" },
  { name: "Philippines", flag: "🇵🇭", cc: "+63" },
  { name: "Poland", flag: "🇵🇱", cc: "+48" },
  { name: "Portugal", flag: "🇵🇹", cc: "+351" },
  { name: "Puerto Rico", flag: "🇵🇷", cc: "+1" },
  { name: "Qatar", flag: "🇶🇦", cc: "+974" },
  { name: "Romania", flag: "🇷🇴", cc: "+40" },
  { name: "Russia", flag: "🇷🇺", cc: "+7" },
  { name: "Rwanda", flag: "🇷🇼", cc: "+250" },
  { name: "Saint Kitts and Nevis", flag: "🇰🇳", cc: "+1" },
  { name: "Saint Lucia", flag: "🇱🇨", cc: "+1" },
  { name: "Saint Vincent and the Grenadines", flag: "🇻🇨", cc: "+1" },
  { name: "Samoa", flag: "🇼🇸", cc: "+685" },
  { name: "San Marino", flag: "🇸🇲", cc: "+378" },
  { name: "Sao Tome and Principe", flag: "🇸🇹", cc: "+239" },
  { name: "Saudi Arabia", flag: "🇸🇦", cc: "+966" },
  { name: "Senegal", flag: "🇸🇳", cc: "+221" },
  { name: "Serbia", flag: "🇷🇸", cc: "+381" },
  { name: "Seychelles", flag: "🇸🇨", cc: "+248" },
  { name: "Sierra Leone", flag: "🇸🇱", cc: "+232" },
  { name: "Singapore", flag: "🇸🇬", cc: "+65" },
  { name: "Slovakia", flag: "🇸🇰", cc: "+421" },
  { name: "Slovenia", flag: "🇸🇮", cc: "+386" },
  { name: "Solomon Islands", flag: "🇸🇧", cc: "+677" },
  { name: "Somalia", flag: "🇸🇴", cc: "+252" },
  { name: "South Africa", flag: "🇿🇦", cc: "+27" },
  { name: "South Korea", flag: "🇰🇷", cc: "+82" },
  { name: "South Sudan", flag: "🇸🇸", cc: "+211" },
  { name: "Spain", flag: "🇪🇸", cc: "+34" },
  { name: "Sri Lanka", flag: "🇱🇰", cc: "+94" },
  { name: "Sudan", flag: "🇸🇩", cc: "+249" },
  { name: "Suriname", flag: "🇸🇷", cc: "+597" },
  { name: "Sweden", flag: "🇸🇪", cc: "+46" },
  { name: "Switzerland", flag: "🇨🇭", cc: "+41" },
  { name: "Syria", flag: "🇸🇾", cc: "+963" },
  { name: "Taiwan", flag: "🇹🇼", cc: "+886" },
  { name: "Tajikistan", flag: "🇹🇯", cc: "+992" },
  { name: "Tanzania", flag: "🇹🇿", cc: "+255" },
  { name: "Thailand", flag: "🇹🇭", cc: "+66" },
  { name: "Timor-Leste", flag: "🇹🇱", cc: "+670" },
  { name: "Togo", flag: "🇹🇬", cc: "+228" },
  { name: "Tonga", flag: "🇹🇴", cc: "+676" },
  { name: "Trinidad and Tobago", flag: "🇹🇹", cc: "+1" },
  { name: "Tunisia", flag: "🇹🇳", cc: "+216" },
  { name: "Turkey", flag: "🇹🇷", cc: "+90" },
  { name: "Turkmenistan", flag: "🇹🇲", cc: "+993" },
  { name: "Tuvalu", flag: "🇹🇻", cc: "+688" },
  { name: "Uganda", flag: "🇺🇬", cc: "+256" },
  { name: "Ukraine", flag: "🇺🇦", cc: "+380" },
  { name: "UAE", flag: "🇦🇪", cc: "+971" },
  { name: "United Kingdom", flag: "🇬🇧", cc: "+44" },
  { name: "United States", flag: "🇺🇸", cc: "+1" },
  { name: "Uruguay", flag: "🇺🇾", cc: "+598" },
  { name: "Uzbekistan", flag: "🇺🇿", cc: "+998" },
  { name: "Vanuatu", flag: "🇻🇺", cc: "+678" },
  { name: "Vatican City", flag: "🇻🇦", cc: "+39" },
  { name: "Venezuela", flag: "🇻🇪", cc: "+58" },
  { name: "Vietnam", flag: "🇻🇳", cc: "+84" },
  { name: "Yemen", flag: "🇾🇪", cc: "+967" },
  { name: "Zambia", flag: "🇿🇲", cc: "+260" },
  { name: "Zimbabwe", flag: "🇿🇼", cc: "+263" },
];

// Most-common renters surface first; everything else stays alphabetical (the
// dropdown has a search box, so deep entries are still one keystroke away).
const PRIORITY = ["Nicaragua", "United States", "Canada"];

export const COUNTRIES: Country[] = [
  ...PRIORITY.map((n) => ALL.find((c) => c.name === n)!),
  ...ALL.filter((c) => !PRIORITY.includes(c.name)),
].map(({ name, flag }) => ({ name, flag }));

// name (lowercased) → dialing code, derived from ALL plus a few aliases the OCR
// layer or users might produce.
const NAME_TO_CC: Record<string, string> = {
  ...Object.fromEntries(ALL.map((c) => [c.name.toLowerCase(), c.cc])),
  "usa": "+1",
  "us": "+1",
  "u.s.a.": "+1",
  "united states of america": "+1",
  "uk": "+44",
  "great britain": "+44",
  "united arab emirates": "+971",
};

export function countryNameToCC(name: string | null | undefined): string | null {
  if (!name) return null;
  const key = name.trim().toLowerCase();
  if (!key) return null;
  return NAME_TO_CC[key] ?? null;
}

export function findCountry(name: string | null | undefined): Country | null {
  if (!name) return null;
  const key = name.trim().toLowerCase();
  if (!key) return null;
  return COUNTRIES.find((c) => c.name.toLowerCase() === key) ?? null;
}
